#!/bin/bash

#PBS -W group_list=tandonr
#PBS -q standard
#PBS -N singularity-hello-world
#PBS -j oe
#PBS -l select=1:ncpus=1:mem=6gb:pcmem=6gb
#PBS -l walltime=00:01:00

printf "Loading singularity!\n"

# Load singularity
module load singularity

printf "Running continer: ... \n"
printf "===================================\n"

# Run the contianer
singularity run $PBS_O_WORKDIR/hello-world.sif

printf "===================================\n"
printf "Container run done!\n"